# safelist
branches:
  only:
  - gh-pages
  - master
  except:
  - gd-files
  - test-edit

language: ruby
before_install:
- travis_retry gem install jekyll
- travis_retry gem install kramdown
script: jekyll build --safe

