# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RDA Registry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  "This is the technical documentation for the RDA: Resource Description and Access published vocabularies and element set."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rdaregistry.info" # the base hostname & protocol for your site
repository: RDARegistry/RDA-Vocabularies

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-feed

data_dir: data

collections:
  terms:
    output: true
    permalink: /termList/:path/

defaults:
  - scope:
      path: ""
      type: terms
    values:
      layout: terms
      datatable: true
